# PHP CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/php

    steps:
      - checkout

      - run: sudo apt update
      # - run: sudo docker-php-ext-install zip

      # quick linting
      - run: php -l *.php

      # deploy
      - add_ssh_keys:
          fingerprints:
            - "SHA256:RTlPWZwfN56ETk4HQpOh6TvrbQziW+s36lcu86aqpdM"
      - run: scp -r * deployer@ssh.ecobricks.org:/var/www/html/wp-content/themes/ecobricks-wp-theme/
